### ISSUE TITLE
How to use the `MultipartHttpServletRequest` class from the default `run()` method?

### ISSUE THREAD

**Issue by doopedia** [daniel-rocha/azure-functions-java-bindings#2]
https://stackoverflow.com/questions/54473126/azure-functions-how-to-use-the-multiparthttpservletrequest-class-from-the-de/54511067

I'm very suffering from the absence of `MultipartHttpServletRequest` or `HttpServletRequest` in the `run()` parameter. Please visit the link above. 

I managed to succeed to fetch a file from the `multipart/form-data` request (assisted by other user) and upload to blob,  but the uploaded one is corrupted.

I downloaded and opened the corrupted file and found that there's some random hexes are misteriously changed to `3f`. Not sure why and when it's happened. maybe uploading to blob?

If there is a `HttpServletRequest` in the `run()`, I shouldn't have suffered like this.

My Azure function is based on the 64bit platfrom. Please notice me if you need more info.

**Comment by daniel-rocha** [comment]
Read the input as a byte array and use Commons File Upload (https://commons.apache.org/proper/commons-fileupload/) to parse the stream into a proper multipart form-data object, then you can read the image.

If you can, however, it's more efficient to send the file directly from the browser to Azure Blob Storage, then have the Blob Storage trigger the function with the file for processing.
